In [1]:
import pandas as pd

columns = ['target','Ids','date','flag','user','texts']

df=pd.read_csv('sentiment140.csv', encoding='latin-1', names=columns)

df.head()

,target,Ids,date,flag,user,texts
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [2]:
df = df[['target', 'texts']]

sentiment_map = {0: 'negative', 4: 'positive'}
df['sentiment'] = df['target'].map(sentiment_map)


df['sentiment'] = df['sentiment'].map({'negative': 0, 'positive': 1})

df.drop('target', axis=1, inplace=True)

df.head()

                                               texts  sentiment
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...          0
1  is upset that he can't update his Facebook by ...          0
2  @Kenichan I dived many times for the ball. Man...          0
3    my whole body feels itchy and like its on fire           0
4  @nationwideclass no, it's not behaving at all....          0

In [3]:
df['sentiment'].value_counts()

sentiment
0    800000
1    800000
Name: count, dtype: int64

In [4]:
import re

def remove_mentions(texts):
    texts = re.sub(r'@\w+', '', texts)  
    return texts

df['clean_text'] = df['texts'].apply(remove_mentions)

print(df[['texts', 'clean_text']].head(10))

                                               texts  \
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  is upset that he can't update his Facebook by ...
2  @Kenichan I dived many times for the ball. Man...
3    my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....
5                      @Kwesidei not the whole crew
6                                        Need a hug
7  @LOLTrish hey  long time no see! Yes.. Rains a...
8               @Tatiana_K nope they didn't have it
9                          @twittera que me muera ?

                                          clean_text
0   http://twitpic.com/2y1zl - Awww, that's a bum...
1  is upset that he can't update his Facebook by ...
2   I dived many times for the ball. Managed to s...
3    my whole body feels itchy and like its on fire
4   no, it's not behaving at all. i'm mad. why am...
5                                not the whole crew
6                                        Need a hug
7   hey  long time no see! Yes.. Rains a bit ,onl...
8                          nope they didn't have it
9                                    que me muera ?

In [5]:
def remove_urls(texts):
    texts = re.sub(r'http\S+', '', texts) 
    return texts

df['clean_text'] = df['clean_text'].apply(remove_urls)


print(df[['texts', 'clean_text']].head(10))

                                               texts  \
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  is upset that he can't update his Facebook by ...
2  @Kenichan I dived many times for the ball. Man...
3    my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....
5                      @Kwesidei not the whole crew
6                                        Need a hug
7  @LOLTrish hey  long time no see! Yes.. Rains a...
8               @Tatiana_K nope they didn't have it
9                          @twittera que me muera ?

                                          clean_text
0    - Awww, that's a bummer.  You shoulda got Da...
1  is upset that he can't update his Facebook by ...
2   I dived many times for the ball. Managed to s...
3    my whole body feels itchy and like its on fire
4   no, it's not behaving at all. i'm mad. why am...
5                                not the whole crew
6                                        Need a hug
7   hey  long time no see! Yes.. Rains a bit ,onl...
8                          nope they didn't have it
9                                    que me muera ?

In [6]:
def remove_hashtags(texts):
    texts = re.sub(r'#\w+', '', texts)  
    return texts

df['clean_text'] = df['clean_text'].apply(remove_hashtags)

print(df[['texts', 'clean_text']].head(10))

                                               texts  \
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  is upset that he can't update his Facebook by ...
2  @Kenichan I dived many times for the ball. Man...
3    my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....
5                      @Kwesidei not the whole crew
6                                        Need a hug
7  @LOLTrish hey  long time no see! Yes.. Rains a...
8               @Tatiana_K nope they didn't have it
9                          @twittera que me muera ?

                                          clean_text
0    - Awww, that's a bummer.  You shoulda got Da...
1  is upset that he can't update his Facebook by ...
2   I dived many times for the ball. Managed to s...
3    my whole body feels itchy and like its on fire
4   no, it's not behaving at all. i'm mad. why am...
5                                not the whole crew
6                                        Need a hug
7   hey  long time no see! Yes.. Rains a bit ,onl...
8                          nope they didn't have it
9                                    que me muera ?

In [7]:
def remove_special_chars_and_numbers(texts):
    texts = re.sub(r'[^A-Za-z\s]', '', texts) 
    return texts

df['clean_text'] = df['clean_text'].apply(remove_special_chars_and_numbers)

print(df[['texts', 'clean_text']].head(10))

                                               texts  \
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  is upset that he can't update his Facebook by ...
2  @Kenichan I dived many times for the ball. Man...
3    my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....
5                      @Kwesidei not the whole crew
6                                        Need a hug
7  @LOLTrish hey  long time no see! Yes.. Rains a...
8               @Tatiana_K nope they didn't have it
9                          @twittera que me muera ?

                                          clean_text
0     Awww thats a bummer  You shoulda got David ...
1  is upset that he cant update his Facebook by t...
2   I dived many times for the ball Managed to sa...
3    my whole body feels itchy and like its on fire
4   no its not behaving at all im mad why am i he...
5                                not the whole crew
6                                        Need a hug
7   hey  long time no see Yes Rains a bit only a ...
8                           nope they didnt have it
9                                     que me muera

In [8]:
def to_lowercase(texts):
    return texts.lower()

df['clean_text'] = df['clean_text'].apply(to_lowercase)

print(df[['texts', 'clean_text']].head(10))

                                               texts  \
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  is upset that he can't update his Facebook by ...
2  @Kenichan I dived many times for the ball. Man...
3    my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....
5                      @Kwesidei not the whole crew
6                                        Need a hug
7  @LOLTrish hey  long time no see! Yes.. Rains a...
8               @Tatiana_K nope they didn't have it
9                          @twittera que me muera ?

                                          clean_text
0     awww thats a bummer  you shoulda got david ...
1  is upset that he cant update his facebook by t...
2   i dived many times for the ball managed to sa...
3    my whole body feels itchy and like its on fire
4   no its not behaving at all im mad why am i he...
5                                not the whole crew
6                                        need a hug
7   hey  long time no see yes rains a bit only a ...
8                           nope they didnt have it
9                                     que me muera

In [9]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\aayush\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\aayush\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\aayush\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\aayush\anaconda3\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\aayush\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\aayush\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [9]:
from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Aayush\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
def remove_stopwords(texts):
    stop_words = set(stopwords.words('english'))
    texts = ' '.join([word for word in texts.split() if word not in stop_words])
    return texts

df['clean_text'] = df['clean_text'].apply(remove_stopwords)

print(df[['texts', 'clean_text']].head(10))

                                               texts  \
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  is upset that he can't update his Facebook by ...
2  @Kenichan I dived many times for the ball. Man...
3    my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....
5                      @Kwesidei not the whole crew
6                                        Need a hug
7  @LOLTrish hey  long time no see! Yes.. Rains a...
8               @Tatiana_K nope they didn't have it
9                          @twittera que me muera ?

                                          clean_text
0  awww thats bummer shoulda got david carr third...
1  upset cant update facebook texting might cry r...
2  dived many times ball managed save rest go bounds
3                   whole body feels itchy like fire
4                           behaving im mad cant see
5                                         whole crew
6                                           need hug
7  hey long time see yes rains bit bit lol im fin...
8                                         nope didnt
9                                          que muera

In [12]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\aayush\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\aayush\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\aayush\anaconda3\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\aayush\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\aayush\anaconda3\lib\site-packages (from scikit-learn) (3.6.0)

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)  

X = vectorizer.fit_transform(df['clean_text'])

print(f"TF-IDF matrix shape: {X.shape}")

TF-IDF matrix shape: (1600000, 5000)

In [14]:
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, df['sentiment'], test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

preds = model.predict(X_test)

print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.78      0.75      0.77    159494
           1       0.76      0.80      0.78    160506

    accuracy                           0.77    320000
   macro avg       0.77      0.77      0.77    320000
weighted avg       0.77      0.77      0.77    320000

In [13]:

import joblib


model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)


joblib.dump(model, "sentiment_model.joblib")

['sentiment_model.joblib']